include:
  - project: "rust/rust-build"
    file: "rust-ci.yml"

workflow:
  rules:
    - if: "$CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'

default:
  image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.81.0-v3
  tags:
    - shared-medium

variables:
  # Ensure submodules are fully initialized
  GIT_SUBMODULE_STRATEGY: recursive

  # The rust registry project
  RUST_REGISTRY: rust/shared/registry

  # The token used to "publish" (clone) the registry
  RUST_REGISTRY_TOKEN: glpat-xzG3FqKqXs4jLwD8Ey2a

  # The URL of the rust registry
  RUST_REGISTRY_URL: ${CI_SERVER_PROTOCOL}://git:${RUST_REGISTRY_TOKEN}@${CI_SERVER_HOST}/${RUST_REGISTRY}.git

# Config git acccess to other repos
.script-config-git:
  script:
    - git config --global url.https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}.insteadOf https://${CI_SERVER_HOST}

stages:
  - lint
  - build
  - doc
  - deploy

.do_fmt_check:
  script:
    - cargo fmt --check

.do_clippy_check:
  script:
    - !reference [.script-config-git, script]
    - cargo clippy -- -D warnings

.do_proton_mail_uniffi_version:
  script:
    - cd proton_mail_uniffi

format:
  stage: lint
  script:
    - !reference [.do_fmt_check, script]

clippy:
  stage: lint
  script:
    - !reference [.do_clippy_check, script]

gopenpgp:
  stage: lint
  script:
    - !reference [.do_gopenpgp_sys_check, script]

build:
  tags:
    - shared-large
  stage: build
  script:
    - !reference [.script-config-git, script]
    - RUSTFLAGS="-C link-arg=-fuse-ld=lld" cargo build
    - RUSTFLAGS="-C link-arg=-fuse-ld=lld" cargo nextest run --color=never

build-macos:
  tags:
    - inbox-tart
  image: "inbox-rust:1.81.0"
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
  script:
    - !reference [.script-config-git, script]
    - cargo build --release
    - cargo nextest run --color=never

build-wasm:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
  script:
    - !reference [.script-config-git, script]
    - cd ./crates/mail-wasm
    - wasm-pack build -d "./web_pkg"
  artifacts:
    name: proton-mail-wasm
    paths:
      - ./crates/mail-wasm/web_pkg
    when: always
    expire_in: 4 hrs

build-ios:
  tags:
    - inbox-tart
  image: "inbox-rust:1.81.0"
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
  script:
    - !reference [.script-config-git, script]
    - cargo build --release --target --target x86_64-apple-ios
    - cargo build --release --target --target aarch64-apple-ios-sim
    - cargo build --release --target --target aarch64-apple-ios
    - rust-build/build_ios_framework_uniffi.sh proton-mail-uniffi ./crates/mail-uniffi/uniffi.toml "./tmp/ios-framework"
    - CRATE_VERSION=$(cargo pkgid --manifest-path=./crates/mail-uniffi/Cargo.toml | cut -d "#" -f2)
    - cd "./tmp/ios-framework/$CRATE_VERSION" && xcodebuild -scheme proton_app_uniffi -destination generic/platform=iOS -configuration="Release build"

  artifacts:
    name: proton-mail-ios
    paths:
      - tmp/ios-framework
    when: always
    expire_in: 4 hrs

build-android:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
  script:
    - !reference [.script-config-git, script]
    - cargo ndk -t "armeabi-v7a" -t "arm64-v8a" -t "x86_64" build --release
    - rust-build/build_android.sh proton-mail-uniffi ./crates/mail-uniffi/uniffi.toml ./crates/mail-uniffi/android/lib/src/main/
    - ./crates/mail-uniffi/android/build-android-archive.sh

  artifacts:
    name: proton-mail-android
    paths:
      - ./crates/mail-uniffi/android/lib/src/main
      - ./crates/mail-uniffi/android/lib/build/
    when: always
    expire_in: 4 hrs

pages:
  stage: doc
  script:
    - echo "CI_PAGES_URL = ${CI_PAGES_URL}"
    - !reference [.script-config-git, script]
    - cargo doc --workspace --all-features --no-deps
    - rm -rf public
    - mv target/doc public
    - echo "<meta http-equiv=\"refresh\" content=\"0; url=$CI_PAGES_URL/proton_mail_uniffi/index.html\">" > public/index.html
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    # allow to test pages in a MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true

publish-crates:
  image: rustlang/rust:nightly
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      variables:
        DRY_RUN: "--dry-run"
  before_script:
    - apt-get update && apt-get install -y python3-packaging
  script:
    - cargo xtask publish $DRY_RUN
      --reg-name proton
      --reg-repo $RUST_REGISTRY_URL
      --name "$GITLAB_USER_NAME"
      --email "$GITLAB_USER_EMAIL"

publish-android:
  stage: deploy
  tags:
    - xlarge-k8s
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
      when: always
      allow_failure: true
  script:
    - ./crates/mail-uniffi/android/publish.sh
  dependencies:
    - build-android
  needs:
    - build-android
  artifacts:
    name: proton-mail-android-lib
    paths:
      - ./crates/mail-uniffi/android/lib/build/outputs/
    when: always
    expire_in: 4 hrs

publish-ios:
  stage: deploy
  tags:
    - xlarge-k8s
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
      when: always
      allow_failure: true
  script:
    - ./crates/mail-uniffi/ios/publish.sh
  dependencies:
    - build-ios
  needs:
    - build-ios
