mod windows_zones {
    include!(concat!(env!("OUT_DIR"), "/windows_zones.rs"));
}

/// Resolves a Windows-specific timezone (as generated by Outlook) to a tzdb
/// zone. Tries the direct Windows key (e.g. "Central European Standard Time")
/// first, and falls back to parsing a display name (e.g.
/// "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris") by looking up each
/// listed city.
pub fn windows_to_tzdb(name: &str) -> Option<&'static str> {
    windows_zones::MAP.get(name).copied().or_else(|| {
        let cities = name.rsplit_once(") ").map_or(name, |(_, rest)| rest);
        cities
            .split(',')
            .find_map(|city| windows_zones::CITY_MAP.get(city.trim()).copied())
    })
}

#[cfg(test)]
mod tests {
    use test_case::test_case;

    #[test_case("W. Europe Standard Time", Some("Europe/Berlin"))]
    #[test_case("Central European Standard Time", Some("Europe/Warsaw"))]
    #[test_case(
        "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
        Some("Europe/Paris")
    )]
    #[test_case(
        "(UTC+01:00) Paris, Brussels, Copenhagen, Madrid",
        Some("Europe/Paris")
    )]
    #[test_case("Anime Time Zone", None)]
    fn windows_to_tzdb(lhs: &str, rhs: Option<&str>) {
        assert_eq!(rhs, super::windows_to_tzdb(lhs));
    }
}
